// Generated by HyperIndex codegen (`envio codegen`). Do not edit manually.
// Wires project-specific types from .envio/types.d.ts into the envio module.
// Run `bun run codegen` (or `pnpm codegen`) to regenerate.
/// <reference path="./.envio/types.d.ts" />
